// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzR78KmSAezrSQFozWxwNxCIeTR_CXqfE',
    appId: '1:570383463237:web:bb2697a187c192323b042c',
    messagingSenderId: '570383463237',
    projectId: 'health-symptom-checker-2073',
    authDomain: 'health-symptom-checker-2073.firebaseapp.com',
    storageBucket: 'health-symptom-checker-2073.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7wC0W0krlbS6qsUIEDCP8hiFmlnVOAZg',
    appId: '1:570383463237:android:aa7ccba44ca0c0ac3b042c',
    messagingSenderId: '570383463237',
    projectId: 'health-symptom-checker-2073',
    storageBucket: 'health-symptom-checker-2073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbkrZ5CISiF2YxcswIQ72-KAwqbPXG1eg',
    appId: '1:570383463237:ios:92933ad1da64eba53b042c',
    messagingSenderId: '570383463237',
    projectId: 'health-symptom-checker-2073',
    storageBucket: 'health-symptom-checker-2073.firebasestorage.app',
    iosBundleId: 'com.example.healthSymptomChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbkrZ5CISiF2YxcswIQ72-KAwqbPXG1eg',
    appId: '1:570383463237:ios:92933ad1da64eba53b042c',
    messagingSenderId: '570383463237',
    projectId: 'health-symptom-checker-2073',
    storageBucket: 'health-symptom-checker-2073.firebasestorage.app',
    iosBundleId: 'com.example.healthSymptomChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzR78KmSAezrSQFozWxwNxCIeTR_CXqfE',
    appId: '1:570383463237:web:5c5d16c46b9177aa3b042c',
    messagingSenderId: '570383463237',
    projectId: 'health-symptom-checker-2073',
    authDomain: 'health-symptom-checker-2073.firebaseapp.com',
    storageBucket: 'health-symptom-checker-2073.firebasestorage.app',
  );
}
